import "./globals.css";

export const metadata = {
  title: "Simple Omelette Recipe",
  description: "Generated by Burak Durmuşoğlu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}

